### ISSUE TITLE
Template for other parts of Germany

### ISSUE THREAD

**Issue by marcosci** [Data-Visualization-Berlin/datavis.berlin#17]
Hi there!

Would it be OK if I use this as a template for dataviz in southern Germany? :) 

Cheers
Marco

**Comment by jnsprnw** [comment]
Hey Marco,
sure, please use it. I would suggest to also cross-reference the two sides.
You can contact me at jonas@datavis.berlin, so that I could give you some assistance on the setup.

Cheers,
Jonas
